// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ss/rpc.proto

package ss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginNotifyRequest) Reset() {
	*x = LoginNotifyRequest{}
	mi := &file_proto_ss_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginNotifyRequest) ProtoMessage() {}

func (x *LoginNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginNotifyRequest.ProtoReflect.Descriptor instead.
func (*LoginNotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *LoginNotifyRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginNotifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginNotifyResponse) Reset() {
	*x = LoginNotifyResponse{}
	mi := &file_proto_ss_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginNotifyResponse) ProtoMessage() {}

func (x *LoginNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginNotifyResponse.ProtoReflect.Descriptor instead.
func (*LoginNotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *LoginNotifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_ss_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_ss_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type LoadRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int64                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRoleRequest) Reset() {
	*x = LoadRoleRequest{}
	mi := &file_proto_ss_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRoleRequest) ProtoMessage() {}

func (x *LoadRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRoleRequest.ProtoReflect.Descriptor instead.
func (*LoadRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *LoadRoleRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type LoadRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRoleResponse) Reset() {
	*x = LoadRoleResponse{}
	mi := &file_proto_ss_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRoleResponse) ProtoMessage() {}

func (x *LoadRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRoleResponse.ProtoReflect.Descriptor instead.
func (*LoadRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *LoadRoleResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LoadRoleResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SaveRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int64                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRoleRequest) Reset() {
	*x = SaveRoleRequest{}
	mi := &file_proto_ss_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoleRequest) ProtoMessage() {}

func (x *SaveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoleRequest.ProtoReflect.Descriptor instead.
func (*SaveRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *SaveRoleRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *SaveRoleRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SaveRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRoleResponse) Reset() {
	*x = SaveRoleResponse{}
	mi := &file_proto_ss_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoleResponse) ProtoMessage() {}

func (x *SaveRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoleResponse.ProtoReflect.Descriptor instead.
func (*SaveRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *SaveRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_ss_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_ss_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_ss_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_proto_ss_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetUserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_ss_rpc_proto protoreflect.FileDescriptor

const file_proto_ss_rpc_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ss/rpc.proto\x12\x02ss\"<\n" +
	"\x12LoginNotifyRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"/\n" +
	"\x13LoginNotifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"?\n" +
	"\x15ValidateTokenResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"#\n" +
	"\x0fLoadRoleRequest\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\x03R\x03rid\"<\n" +
	"\x10LoadRoleResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"7\n" +
	"\x0fSaveRoleRequest\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\x03R\x03rid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\",\n" +
	"\x10SaveRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"&\n" +
	"\x12CreateUserResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"^\n" +
	"\x0fGetUserResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found2\x94\x01\n" +
	"\fLoginService\x12>\n" +
	"\vNotifyLogin\x12\x16.ss.LoginNotifyRequest\x1a\x17.ss.LoginNotifyResponse\x12D\n" +
	"\rValidateToken\x12\x18.ss.ValidateTokenRequest\x1a\x19.ss.ValidateTokenResponse2\xea\x01\n" +
	"\tDBService\x125\n" +
	"\bLoadRole\x12\x13.ss.LoadRoleRequest\x1a\x14.ss.LoadRoleResponse\x125\n" +
	"\bSaveRole\x12\x13.ss.SaveRoleRequest\x1a\x14.ss.SaveRoleResponse\x12;\n" +
	"\n" +
	"CreateUser\x12\x15.ss.CreateUserRequest\x1a\x16.ss.CreateUserResponse\x122\n" +
	"\aGetUser\x12\x12.ss.GetUserRequest\x1a\x13.ss.GetUserResponseB#Z!github.com/luckinbyte/wg_ai/proto/ssb\x06proto3"

var (
	file_proto_ss_rpc_proto_rawDescOnce sync.Once
	file_proto_ss_rpc_proto_rawDescData []byte
)

func file_proto_ss_rpc_proto_rawDescGZIP() []byte {
	file_proto_ss_rpc_proto_rawDescOnce.Do(func() {
		file_proto_ss_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ss_rpc_proto_rawDesc), len(file_proto_ss_rpc_proto_rawDesc)))
	})
	return file_proto_ss_rpc_proto_rawDescData
}

var file_proto_ss_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_ss_rpc_proto_goTypes = []any{
	(*LoginNotifyRequest)(nil),    // 0: ss.LoginNotifyRequest
	(*LoginNotifyResponse)(nil),   // 1: ss.LoginNotifyResponse
	(*ValidateTokenRequest)(nil),  // 2: ss.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 3: ss.ValidateTokenResponse
	(*LoadRoleRequest)(nil),       // 4: ss.LoadRoleRequest
	(*LoadRoleResponse)(nil),      // 5: ss.LoadRoleResponse
	(*SaveRoleRequest)(nil),       // 6: ss.SaveRoleRequest
	(*SaveRoleResponse)(nil),      // 7: ss.SaveRoleResponse
	(*CreateUserRequest)(nil),     // 8: ss.CreateUserRequest
	(*CreateUserResponse)(nil),    // 9: ss.CreateUserResponse
	(*GetUserRequest)(nil),        // 10: ss.GetUserRequest
	(*GetUserResponse)(nil),       // 11: ss.GetUserResponse
}
var file_proto_ss_rpc_proto_depIdxs = []int32{
	0,  // 0: ss.LoginService.NotifyLogin:input_type -> ss.LoginNotifyRequest
	2,  // 1: ss.LoginService.ValidateToken:input_type -> ss.ValidateTokenRequest
	4,  // 2: ss.DBService.LoadRole:input_type -> ss.LoadRoleRequest
	6,  // 3: ss.DBService.SaveRole:input_type -> ss.SaveRoleRequest
	8,  // 4: ss.DBService.CreateUser:input_type -> ss.CreateUserRequest
	10, // 5: ss.DBService.GetUser:input_type -> ss.GetUserRequest
	1,  // 6: ss.LoginService.NotifyLogin:output_type -> ss.LoginNotifyResponse
	3,  // 7: ss.LoginService.ValidateToken:output_type -> ss.ValidateTokenResponse
	5,  // 8: ss.DBService.LoadRole:output_type -> ss.LoadRoleResponse
	7,  // 9: ss.DBService.SaveRole:output_type -> ss.SaveRoleResponse
	9,  // 10: ss.DBService.CreateUser:output_type -> ss.CreateUserResponse
	11, // 11: ss.DBService.GetUser:output_type -> ss.GetUserResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ss_rpc_proto_init() }
func file_proto_ss_rpc_proto_init() {
	if File_proto_ss_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ss_rpc_proto_rawDesc), len(file_proto_ss_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ss_rpc_proto_goTypes,
		DependencyIndexes: file_proto_ss_rpc_proto_depIdxs,
		MessageInfos:      file_proto_ss_rpc_proto_msgTypes,
	}.Build()
	File_proto_ss_rpc_proto = out.File
	file_proto_ss_rpc_proto_goTypes = nil
	file_proto_ss_rpc_proto_depIdxs = nil
}
