server:
  grpc_port: 50052

database:
  mysql:
    host: "127.0.0.1"
    port: 3306
    database: "game"
    username: "root"
    password: "xxx"
    max_open: 100
    max_idle: 20
  redis:
    host: "127.0.0.1"
    port: 6379
    db: 0
    pool_size: 100

log:
  level: "info"
